local Tools = require("src.Tools")
local Scalars = require("src.Scalars")
local MatrixAlgebra = require("src.MatrixAlgebra")
local Interpolation = require("src.Interpolation")
local SymbolicAlgebra = require("src.SymbolicAlgebra")
local ODE = require("src.ODE")

local test = Interpolation.Chebyshev.makeInterpolant(function (x) return math.exp(x) end, 0, 1, 20)
local testPrime = test:derivative()
local testInverse = test:inverse()

print("Interpolant Tests")

print("Solve test(x) = 2    ", Tools.list.tostring(test:solve(2)))
print("Solve test'(x) = 2   ", Tools.list.tostring(testPrime:solve(2)))
print("Solve exp(x) = 2    ", Tools.solve.regulaFalsi(math.exp, 2, 0, 1))
print("exp(0.69314718)   ", math.exp(0.69314718))
print("Evaluate test^(-1)(2)", testInverse:evaluate(2))
print("exp(0.405465)        ", math.exp(0.405465))
print("Compute test max     ", test:max())
print("exp(1)               ", math.exp(1))